### ISSUE TITLE
Expand numbers from BamStats

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#104]
Percentage mapped reads is reporter per lane now. We care about the overall mapped reads per sample, however, so we want to make that conversion. This is what we see now:

```yaml
    SIB909A8.141216_HB05PADXX_ACTTGA.lane1:
      BamStats:
        percentag_mapped_reads: 99.7589420977317
```

To make an accurate average we would need the total number of reads and total number of mapped reads. We can't infer that from only this number. Perhaps one "lane" is undetermined reads and then we need to know how many read (pairs) was in that file which we get the mapped percentage number from.

Perhaps also update the key: `percentag_mapped_reads` to `percentage_mapped_reads` ;)
